[package]
name = "repostats"
version = "0.1.1"
edition = "2024"

[[bin]]
name = "repostats"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
walkdir = "2.5"
colored = "2.1"
